name: Fetch TLE Data

on: 
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-tle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Fetch ISS TLE
        run: |
          curl --fail -s "https://celestrak.org/NORAD/elements/gp.php?CATNR=25544&FORMAT=TLE" > src/data/detailed.tle

      - name: Fetch Full TLE
        run: |
          curl --fail -s "https://celestrak.org/NORAD/elements/gp.php?GROUP=active&FORMAT=tle" > src/data/full.tle

      - name: Commit + Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add src/data/detailed.tle
          git add src/data/full.tle
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto Update Daily TLE Data" && git push)

        
    
  
